var group___group___l_e_ds =
[
    [ "ADAFRUITU4", "group___group___l_e_ds___a_d_a_f_r_u_i_t_u4.html", "group___group___l_e_ds___a_d_a_f_r_u_i_t_u4" ],
    [ "ATAVRUSBRF01", "group___group___l_e_ds___a_t_a_v_r_u_s_b_r_f01.html", "group___group___l_e_ds___a_t_a_v_r_u_s_b_r_f01" ],
    [ "BENITO", "group___group___l_e_ds___b_e_n_i_t_o.html", "group___group___l_e_ds___b_e_n_i_t_o" ],
    [ "BLACKCAT", "group___group___l_e_ds___b_l_a_c_k_c_a_t.html", "group___group___l_e_ds___b_l_a_c_k_c_a_t" ],
    [ "BUI", "group___group___l_e_ds___b_u_i.html", "group___group___l_e_ds___b_u_i" ],
    [ "BUMBLEB", "group___group___l_e_ds___b_u_m_b_l_e_b.html", "group___group___l_e_ds___b_u_m_b_l_e_b" ],
    [ "CULV3", "group___group___l_e_ds___c_u_l_v3.html", "group___group___l_e_ds___c_u_l_v3" ],
    [ "EVK1101", "group___group___l_e_ds___e_v_k1101.html", "group___group___l_e_ds___e_v_k1101" ],
    [ "EVK527", "group___group___l_e_ds___e_v_k527.html", "group___group___l_e_ds___e_v_k527" ],
    [ "JMDBU2", "group___group___l_e_ds___j_m_d_b_u2.html", "group___group___l_e_ds___j_m_d_b_u2" ],
    [ "MAXIMUS", "group___group___l_e_ds___m_a_x_i_m_u_s.html", "group___group___l_e_ds___m_a_x_i_m_u_s" ],
    [ "MICROSIN162", "group___group___l_e_ds___m_i_c_r_o_s_i_n162.html", "group___group___l_e_ds___m_i_c_r_o_s_i_n162" ],
    [ "MINIMUS", "group___group___l_e_ds___m_i_n_i_m_u_s.html", "group___group___l_e_ds___m_i_n_i_m_u_s" ],
    [ "OLIMEX162", "group___group___l_e_ds___o_l_i_m_e_x162.html", "group___group___l_e_ds___o_l_i_m_e_x162" ],
    [ "RZUSBSTICK", "group___group___l_e_ds___r_z_u_s_b_s_t_i_c_k.html", "group___group___l_e_ds___r_z_u_s_b_s_t_i_c_k" ],
    [ "SPARKFUN8U2", "group___group___l_e_ds___s_p_a_r_k_f_u_n8_u2.html", "group___group___l_e_ds___s_p_a_r_k_f_u_n8_u2" ],
    [ "STK525", "group___group___l_e_ds___s_t_k525.html", "group___group___l_e_ds___s_t_k525" ],
    [ "STK526", "group___group___l_e_ds___s_t_k526.html", "group___group___l_e_ds___s_t_k526" ],
    [ "TEENSY", "group___group___l_e_ds___t_e_e_n_s_y.html", "group___group___l_e_ds___t_e_e_n_s_y" ],
    [ "UDIP", "group___group___l_e_ds___u_d_i_p.html", "group___group___l_e_ds___u_d_i_p" ],
    [ "UNO", "group___group___l_e_ds___u_n_o.html", "group___group___l_e_ds___u_n_o" ],
    [ "USBFOO", "group___group___l_e_ds___u_s_b_f_o_o.html", "group___group___l_e_ds___u_s_b_f_o_o" ],
    [ "USBKEY", "group___group___l_e_ds___u_s_b_k_e_y.html", "group___group___l_e_ds___u_s_b_k_e_y" ],
    [ "USBTINYMKII", "group___group___l_e_ds___u_s_b_t_i_n_y_m_k_i_i.html", "group___group___l_e_ds___u_s_b_t_i_n_y_m_k_i_i" ],
    [ "XPLAIN", "group___group___l_e_ds___x_p_l_a_i_n.html", "group___group___l_e_ds___x_p_l_a_i_n" ],
    [ "Functions", "group___group___l_e_ds.html", "group___group___l_e_ds_dup" ]
];